<a href="https://colab.research.google.com/github/likhith-t-25/human-activity-recognition/blob/main/Copy_of_Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
# prompt: human activity recognition -a model that identifies physical activities using sensor data give python code it should contains It's great to hear that you are working on a Human Activity Recognition (HAR) project using sensor data. This is a highly relevant domain with applications in healthcare, fitness monitoring, and smart environments. modify code only by using gyroscopic.the gyroscopic sensor data should be input given by user from file manager fix the below error and modify the code ValueError: Unknown label type: continuous. Maybe you are trying to fit a classifier, which expects discrete classes on a regression target with continuous values.fix the error Input y contains NaN and modify the code fix the error "['Activity'] not found in axis" fix the error  name 'df' is not defined and modify the code

import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix
from google.colab import files

# Upload the gyroscopic sensor data file
uploaded = files.upload()

# Get the filename from the uploaded files
for fn in uploaded.keys():
  filename = fn

try:
    # Load the dataset with proper handling of NaN values
    df = pd.read_csv(filename)

    # Check for 'Activity' column and handle its absence gracefully
    if 'Activity' not in df.columns:
        print(f"Error: 'Activity' column not found in the uploaded file '{filename}'. Please ensure the file contains an 'Activity' column.")
        exit()  # Or handle the error differently, e.g., prompt for a new file

    # Handle NaN values by filling them with the mean of each column
    df.fillna(df.mean(), inplace=True)

    # Select relevant features (gyroscopic data) -  Modify this based on your data columns
    features = ['gyro_x', 'gyro_y', 'gyro_z']  # Replace with actual column names
    if not all(feature in df.columns for feature in features):
        print("Error: Not all specified gyroscopic features were found in the dataset. Please check your feature names.")
        exit()
    X = df[features]
    y = df['Activity']

    # Convert 'Activity' column to numerical labels if they are strings
    if not pd.api.types.is_numeric_dtype(y):
        y = pd.factorize(y)[0]


    # Split data into training and testing sets
    X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


    # Feature scaling
    scaler = StandardScaler()
    X_train = scaler.fit_transform(X_train)
    X_test = scaler.transform(X_test)

    # Initialize and train a RandomForestClassifier (you can change the model)
    model = RandomForestClassifier(random_state=42)
    model.fit(X_train, y_train)

    # Make predictions
    y_pred = model.predict(X_test)

    # Evaluate the model
    print(classification_report(y_test, y_pred))
    print(confusion_matrix(y_test, y_pred))

except FileNotFoundError:
    print(f"Error: File '{filename}' not found.")
except pd.errors.EmptyDataError:
    print(f"Error: File '{filename}' is empty.")
except KeyError as e:
    print(f"Error: Column '{e}' not found in the dataset.")
except Exception as e:  # Catch other potential errors
    print(f"An unexpected error occurred: {e}")


Saving gyroscopic .csv to gyroscopic  (1).csv
              precision    recall  f1-score   support

           1       0.00      0.00      0.00       1.0
           2       0.00      0.00      0.00       1.0
           3       0.00      0.00      0.00       0.0

    accuracy                           0.00       2.0
   macro avg       0.00      0.00      0.00       2.0
weighted avg       0.00      0.00      0.00       2.0

[[0 0 1]
 [0 0 1]
 [0 0 0]]


/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_